version: "3"
services:
  postgres: 
    image: postgres:10
    container_name: "postgres"
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_book
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./postgres/initd:/docker-entrypoint-initdb.d